(ns aws-panel.notifiers.fixtures)

(def raw-ec2-instances
  [{:monitoring {:state "disabled"}, 
    :tags [{:value "false", :key "stackdriver_monitor"} 
           {:value "jenkins-agent", :key "environment_name"} 
           {:value "jenkins-agent", :key "Name"}], 
    :root-device-type "ebs", 
    :private-dns-name "", 
    :hypervisor "xen", 
    :subnet-id "subnet-dfad4fb6", 
    :key-name "sppdev", 
    :architecture "x86_64", 
    :security-groups [{:group-id "sg-ac5447c0", 
                       :group-name "VPC-BuildAgent"}], 
    :source-dest-check true, 
    :root-device-name "/dev/sda1", 
    :virtualization-type "paravirtual", 
    :product-codes [], 
    :instance-type "c3.large", 
    :ami-launch-index 0, 
    :image-id "ami-4a605929", 
    :state {:name "running", :code 16}, 
    :state-transition-reason "", 
    :network-interfaces [{:description "", 
                          :subnet-id "subnet-dfad4fb6", 
                          :source-dest-check true, 
                          :private-ip-addresses [{:private-ip-address "10.63.1.198", :primary true}], 
                          :network-interface-id "eni-31fb387b", 
                          :vpc-id "vpc-c7ad4fae", 
                          :mac-address "06:f1:e5:fa:f2:6b", 
                          :status "in-use", 
                          :private-ip-address "10.63.1.198", 
                          :owner-id "949364753207", 
                          :groups [{:group-id "sg-ac5447c0", :group-name "VPC-BuildAgent"}], 
                          :attachment {:status "attached", 
                                       :attachment-id "eni-attach-4a9b01ed", 
                                       :device-index 0, 
                                       :attach-time "2016-12-01T01:41:34.000Z", 
                                       :delete-on-termination true}}], 
    :vpc-id "vpc-c7ad4fae", 
    :ebs-optimized false, 
    :instance-id "i-ffb9e550", 
    :iam-instance-profile {:id "AIPAJ2RNPGZOGYQREFCCE", 
                           :arn "arn:aws:iam::949364753207:instance-profile/atlas"}, 
    :kernel-id "aki-31990e0b", 
    :public-dns-name "", 
    :private-ip-address "10.63.1.198", 
    :placement {:tenancy "default", 
                :group-name "", 
                :availability-zone "ap-southeast-2a"}, 
    :client-token "da0543c3-2f2b-4d9e-b47c-517583e97811", 
    :launch-time "2016-12-01T01:41:34", 
    :block-device-mappings [{:ebs {:status "attached", 
                                   :volume-id "vol-a157412c", 
                                   :attach-time "2016-12-01T01:41:35.000Z", 
                                   :delete-on-termination true}, 
                             :device-name "/dev/sda1"}]
    } 
   {:monitoring {:state "disabled"}, 
    :tags [{:value "2.508.(HEAD detached at b5a34f4)-b5a34f4d3f90a01355a53d6c68b401fc224e757e()", 
            :key "Name"} 
           {:value "devbox", :key "environment_name"} 
           {:value "25-Jan-2017 13:42", :key "created_on"} 
           {:value "", :key "created_by"}], 
    :root-device-type "ebs", 
    :private-dns-name "", 
    :hypervisor "xen", 
    :subnet-id "subnet-38b45651", 
    :key-name "sppdev", 
    :architecture "x86_64", 
    :security-groups [{:group-id "sg-5a061536", 
                       :group-name "VPC-StandAlone"}], 
    :source-dest-check true, 
    :root-device-name "/dev/sda1", 
    :virtualization-type "paravirtual", 
    :product-codes [], 
    :instance-type "m1.large", 
    :ami-launch-index 0, 
    :image-id "ami-36232455", 
    :state {:name "running", :code 16}, 
    :state-transition-reason "", 
    :network-interfaces [{:description "", 
                          :subnet-id "subnet-38b45651", 
                          :source-dest-check true, 
                          :private-ip-addresses [{:private-ip-address "10.63.20.57", 
                                                  :primary true}], 
                          :network-interface-id "eni-e498669f", 
                          :vpc-id "vpc-c7ad4fae", 
                          :mac-address "02:c8:7c:7f:c5:21", 
                          :status "in-use", 
                          :private-ip-address "10.63.20.57", 
                          :owner-id "949364753207", 
                          :groups [{:group-id "sg-5a061536", 
                                    :group-name "VPC-StandAlone"}], 
                          :attachment {:status "attached", 
                                       :attachment-id "eni-attach-6c18f902", 
                                       :device-index 0, 
                                       :attach-time "2017-01-25T13:31:31.000Z", 
                                       :delete-on-termination true}}], 
    :vpc-id "vpc-c7ad4fae", 
    :ebs-optimized false, 
    :instance-id "i-02042de72cd06db62", 
    :iam-instance-profile {:id "AIPAJWVHOM6BKZ5GTPGN4", 
                           :arn "arn:aws:iam::949364753207:instance-profile/atlas-standalone"}, 
    :kernel-id "aki-31990e0b", 
    :public-dns-name "", 
    :private-ip-address "10.63.20.57", 
    :placement {:tenancy "default", 
                :group-name "", 
                :availability-zone "ap-southeast-2b"}, 
    :client-token "1e2885cf-c86d-46c5-9a04-96c42c960bf0", 
    :launch-time "2017-01-25T13:31:31.000Z", 
    :block-device-mappings [{:ebs {:status "attached", 
                                   :volume-id "vol-0dace6eccdd9e63d6", 
                                   :attach-time "2017-01-25T13:31:32.000Z", 
                                   :delete-on-termination true}, 
                             :device-name "/dev/sda1"}]}]
  ) 
